version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "traffic_police_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    ports:
      - "5440:5432"
    volumes:
      - pg_vol:/var/lib/postgresql/data
    networks:
      - service_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "traffic_police_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13.0-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_vol:/var/lib/rabbitmq
    networks:
      - service_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 10

  service:
    build: ./service
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - cases_vol:/app/cases
      - experts_vol:/app/experts
    networks:
      - service_network

  fine_notification:
    build: ./fine_notification
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - service_network

volumes:
  pg_vol:
  cases_vol:
  experts_vol:
  rabbitmq_vol:

networks:
  service_network:
    driver: bridge